import type { Metadata } from "next";
import { sfProDisplay, sfProText } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${sfProDisplay.variable} ${sfProText.variable}`}>
      <body className={`${sfProDisplay.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}